name: Scrape data

on:
  schedule:
    - cron:  '0 */3 * * *' # every three hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build
      run: npm install
  
    - name: Scrape
      run: npm run scrape

    - uses: mikeal/publish-to-github-action@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
